/**
 * PIXEL CREW — Resilience & Reliability Engine
 * 
 * Synthesizes retry policies with exponential backoff & full jitter,
 * circuit breakers, and graceful shutdown signal handlers.
 */

export class ResilienceEngine {
  /**
   * Synthesize resilience utilities
   * @param {object} architecture 
   * @returns {object} Map of filename -> content
   */
  static generateResilienceSuite(architecture = {}) {
    const files = {};

    // 1. Retry with Exponential Backoff & Jitter
    files['src/infrastructure/resilience.ts'] = `/**
 * Enterprise Resilience Utilities: Retries, Backoff & Circuit Breakers
 * Auto-generated by Pixel Crew Resilience Engine
 */

export interface RetryOptions {
  maxRetries?: number;
  baseDelayMs?: number;
  maxDelayMs?: number;
  retryOnStatus?: number[];
}

/**
 * Executes an async operation with exponential backoff and full jitter
 */
export async function withRetry<T>(
  operation: () => Promise<T>,
  options: RetryOptions = {}
): Promise<T> {
  const {
    maxRetries = 3,
    baseDelayMs = 200,
    maxDelayMs = 3000
  } = options;

  let attempt = 0;
  while (true) {
    try {
      return await operation();
    } catch (error) {
      attempt++;
      if (attempt > maxRetries) {
        throw error;
      }

      // Full Jitter Formula: sleep = rand(0, min(maxDelay, baseDelay * 2^attempt))
      const expDelay = Math.min(maxDelayMs, baseDelayMs * Math.pow(2, attempt));
      const jitterDelay = Math.floor(Math.random() * expDelay);

      await new Promise(resolve => setTimeout(resolve, jitterDelay));
    }
  }
}

/**
 * Tri-State Circuit Breaker
 */
export class CircuitBreaker {
  private failureCount = 0;
  private state: "CLOSED" | "OPEN" | "HALF_OPEN" = "CLOSED";
  private nextAttempt = Date.now();

  constructor(
    private readonly threshold: number = 5,
    private readonly resetTimeoutMs: number = 30000
  ) {}

  async execute<T>(action: () => Promise<T>): Promise<T> {
    if (this.state === "OPEN") {
      if (Date.now() > this.nextAttempt) {
        this.state = "HALF_OPEN";
      } else {
        throw new Error("Circuit breaker is OPEN: service temporarily unavailable");
      }
    }

    try {
      const result = await action();
      this.onSuccess();
      return result;
    } catch (error) {
      this.onFailure();
      throw error;
    }
  }

  private onSuccess() {
    this.failureCount = 0;
    this.state = "CLOSED";
  }

  private onFailure() {
    this.failureCount++;
    if (this.failureCount >= this.threshold) {
      this.state = "OPEN";
      this.nextAttempt = Date.now() + this.resetTimeoutMs;
    }
  }
}
`;

    // 2. Graceful Shutdown Coordinator
    files['src/infrastructure/shutdown.ts'] = `/**
 * Graceful Process Shutdown Handler (SIGTERM, SIGINT)
 */

type CleanupFunction = () => Promise<void> | void;
const cleanupHandlers: CleanupFunction[] = [];

export function registerCleanupHandler(fn: CleanupFunction): void {
  cleanupHandlers.push(fn);
}

export function setupGracefulShutdown(): void {
  const shutdown = async (signal: string) => {
    console.info(\`Received \${signal}. Initiating graceful shutdown sequence...\`);
    for (const handler of cleanupHandlers) {
      try {
        await handler();
      } catch (err) {
        console.error("Error during cleanup handler execution:", err);
      }
    }
    process.exit(0);
  };

  process.on("SIGTERM", () => shutdown("SIGTERM"));
  process.on("SIGINT", () => shutdown("SIGINT"));
}
`;

    return files;
  }
}
